import { createElement } from '@lwc/engine-dom';
import Q17_RecordForm_LDS from 'c/q17_RecordForm_LDS';

describe('c-q17-record-form-lds', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-q17-record-form-lds', {
            is: Q17_RecordForm_LDS
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});