import { createElement } from '@lwc/engine-dom';
import L12_ForEachLoopLWC from 'c/l12_ForEachLoopLWC';

describe('c-l12-for-each-loop-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l12-for-each-loop-lwc', {
            is: L12_ForEachLoopLWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});