import { createElement } from '@lwc/engine-dom';
import G7_trackDecoratorsInLWC from 'c/g7_trackDecoratorsInLWC';

describe('c-g7-track-decorators-in-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-g7-track-decorators-in-lwc', {
            is: G7_trackDecoratorsInLWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});