import { createElement } from '@lwc/engine-dom';
import J10_ConditionalOperatorsInLwc from 'c/j10_ConditionalOperatorsInLwc';

describe('c-j10-conditional-operators-in-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-j10-conditional-operators-in-lwc', {
            is: J10_ConditionalOperatorsInLwc
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});