import { createElement } from '@lwc/engine-dom';
import S19_RecordForm_ReadOnlyMode from 'c/s19_RecordForm_ReadOnlyMode';

describe('c-s19-record-form-read-only-mode', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-s19-record-form-read-only-mode', {
            is: S19_RecordForm_ReadOnlyMode
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});