import { createElement } from '@lwc/engine-dom';
import N14_ComboBoxWithDataTable from 'c/n14_ComboBoxWithDataTable';

describe('c-n14-combo-box-with-data-table', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-n14-combo-box-with-data-table', {
            is: N14_ComboBoxWithDataTable
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});