import { createElement } from '@lwc/engine-dom';
import O15_RecordViewForm_LDS from 'c/o15_RecordViewForm_LDS';

describe('c-o15-record-view-form-lds', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-o15-record-view-form-lds', {
            is: O15_RecordViewForm_LDS
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});